# Markdownlint configuration for KCS project
default: true

# Line length - allow longer lines for URLs and code examples
MD013:
  line_length: 100
  code_blocks: false
  tables: false
  headings: false

# Fenced code blocks should have language - but allow some exceptions for simple configs
MD040: false
