# Rustfmt configuration for kcs-graph call graph data structures
# Optimized for database entities and graph algorithm readability
# Only using stable rustfmt options for Rust 1.89.0

# Basic formatting options (stable)
edition = "2021"
hard_tabs = false
tab_spaces = 4
max_width = 100
use_small_heuristics = "Default"

# Import organization (stable)
reorder_imports = true
reorder_modules = true

# Function and struct formatting (stable)
fn_params_layout = "Tall"
fn_call_width = 80
array_width = 80

# Chain formatting for graph node access (stable)
chain_width = 80
single_line_if_else_max_width = 50
force_explicit_abi = true

# Pattern and match formatting (stable)
match_arm_leading_pipes = "Never"
match_block_trailing_comma = true

# String and literal formatting (stable)
attr_fn_like_width = 80

# Newline and spacing (stable)
newline_style = "Unix"
remove_nested_parens = true

# Error recovery options removed (nightly-only):
# - error_on_line_overflow = false
# - error_on_unformatted = false

# Nightly-only options removed to eliminate warnings:
# - group_imports = "StdExternalCrate"
# - imports_granularity = "Crate"
# - struct_field_align_threshold = 25
# - control_brace_style = "AlwaysSameLine"
# - brace_style = "SameLineWhere"
# - indent_style = "Block"
# - comment_width = 80
# - doc_comment_code_block_width = 80
# - format_code_in_doc_comments = true
# - format_strings = true
# - format_macro_matchers = true
# - condense_wildcard_suffixes = true
# - match_arm_blocks = true
# - string_lit_width = 80
# - combine_control_expr = false
# - overflow_delimited_expr = true
# - struct_lit_single_line = false
# - enum_discrim_align_threshold = 25
# - spaces_around_ranges = false
# - type_punctuation_density = "Wide"
# - trailing_comma = "Vertical"
# - trailing_semicolon = true
# - where_single_line = true
# - force_multiline_blocks = false
