# Rustfmt configuration for kcs-graph call graph data structures
# Optimized for database entities and graph algorithm readability

# Basic formatting options
edition = "2021"
hard_tabs = false
tab_spaces = 4
max_width = 100
use_small_heuristics = "Default"

# Import organization for graph and database modules
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
reorder_imports = true
reorder_modules = true

# Function and struct formatting for graph entities
fn_params_layout = "Tall"
fn_call_width = 80
struct_field_align_threshold = 25
array_width = 80

# Control flow formatting for graph algorithms
control_brace_style = "AlwaysSameLine"
brace_style = "SameLineWhere"
indent_style = "Block"

# Comment formatting for graph documentation
comment_width = 80
doc_comment_code_block_width = 80
format_code_in_doc_comments = true
format_strings = true
format_macro_matchers = true

# Chain formatting for graph node access
chain_width = 80
single_line_if_else_max_width = 50
force_explicit_abi = true

# Pattern and match formatting for graph types
condense_wildcard_suffixes = true
match_arm_blocks = true
match_arm_leading_pipes = "Never"
match_block_trailing_comma = true

# String and literal formatting
string_lit_width = 80
attr_fn_like_width = 80

# Advanced formatting options for graph structures
combine_control_expr = false
overflow_delimited_expr = true
struct_lit_single_line = false
enum_discrim_align_threshold = 25

# Newline and spacing
newline_style = "Unix"
remove_nested_parens = true
spaces_around_ranges = false
type_punctuation_density = "Wide"

# Trailing elements
trailing_comma = "Vertical"
trailing_semicolon = true

# Where clause formatting for graph generic bounds
where_single_line = true
force_multiline_blocks = false

# Error recovery
error_on_line_overflow = false
error_on_unformatted = false
ignore = []
